version: '3'

services:
  flask_blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:123@pg:5432/flask_blog
    ports:
      - "5050:5000"
#    this only for developement mounted current folder to
    volumes:
      - ./:/var/app
    depends_on:
      - pg

  pg:
    image: postgres
    environment:
      POSTGRES_DB: flask_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data: