version: '3'

services:
  flask_blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:123@pg:5432/flask_blog
    ports:
      - "5050:5000"
    volumes:
      - ./:/var/app
    depends_on:
      - pg
    restart: on-failure:5 

  flask_blog_prod:
    build:
      context: .
      dockerfile: docker-build/flask_blog_prod/Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:123@pg:5432/flask_blog
    ports:
      - "80:80"
    depends_on:
      - pg
    restart: on-failure:5 

  pg:
    image: postgres
    environment:
      POSTGRES_DB: flask_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  db-data: