"""Initial migration

Revision ID: 26813cecf850
Revises: 
Create Date: 2021-12-13 23:32:50.169511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26813cecf850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    posts_table = op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_link_access', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('header')
    )
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )

    # INIT SEED DATA
    sql_cache = open("db_cache/flask_blog_public_posts.sql")
    op.execute(sql_cache.read())
    from services.logger_service import main_logger
    main_logger.log("SQL_CACHE_EXECUTED, COMMAND:", sql_cache.read())
    # ### end Alembic commands ###

    op.bulk_insert(posts_table,
                   [
                       {'id': 1,
                        'header': 'test_header',
                        'body': 'test_body',
                        'is_published': True,
                        'is_deleted': False,
                        'is_link_access': False}
                   ])
    main_logger.log("-----bulk_insert, posts_table")

    op.bulk_insert(users_table,
                   [
                        {'login': "admin",
                        'password': '78bba5e38bacdee73bd20dd60d9cd47a',
                        'is_deleted': False,
                        }
                    ])
    main_logger.log("-----bulk_insert, users_table")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('posts')
    # ### end Alembic commands ###
